import type { Course } from "@/lib/types";

export const MOCK_COURSES: Course[] = [
  {
    id: "co1",
    titleFa: "دوره مدیتیشن مقدماتی",
    titleEn: "Beginner Meditation Course",
    descriptionFa: "یک دوره ۸ هفته‌ای کامل برای آشنایی با اصول مدیتیشن. شامل جلسات ویدیویی هفتگی، تمرین‌های عملی، فایل‌های صوتی راهنما و پشتیبانی گروهی. مناسب برای افرادی که هیچ تجربه قبلی در مدیتیشن ندارند.",
    price: 1500000,
    instructor: "استاد علی محمدی",
    instructorImage: "/images/instructors/ali-mohammadi.jpg",
    image: "/images/courses/meditation-beginner.jpg",
    durationHours: 24,
    active: true,
    createdAt: "2024-01-15T09:00:00Z",
  },
  {
    id: "co2",
    titleFa: "چاکرا درمانی پیشرفته",
    titleEn: "Advanced Chakra Healing",
    descriptionFa: "دوره تخصصی چاکرا درمانی در ۱۲ جلسه. آموزش تشخیص انسداد چاکراها، تکنیک‌های باز کردن و متعادل‌سازی، کار با کریستال‌ها و رنگ‌ها. پیش‌نیاز: آشنایی اولیه با چاکراها.",
    price: 2800000,
    instructor: "دکتر سارا احمدی",
    instructorImage: "/images/instructors/sara-ahmadi.jpg",
    image: "/images/courses/chakra-advanced.jpg",
    durationHours: 36,
    active: true,
    createdAt: "2024-02-01T10:00:00Z",
  },
  {
    id: "co3",
    titleFa: "یوگا و انرژی درمانی",
    titleEn: "Yoga & Energy Healing",
    descriptionFa: "ترکیبی از حرکات یوگا و تکنیک‌های انرژی درمانی. این دوره ۱۰ جلسه‌ای شامل آموزش آساناهای پایه، پرانایاما (تمرینات تنفسی)، و روش‌های هدایت انرژی پرانا در بدن است.",
    price: 2200000,
    instructor: "مینا رضوی",
    instructorImage: "/images/instructors/mina-razavi.jpg",
    image: "/images/courses/yoga-energy.jpg",
    durationHours: 20,
    active: true,
    createdAt: "2024-02-20T11:00:00Z",
  },
  {
    id: "co4",
    titleFa: "کریستال تراپی مقدماتی",
    titleEn: "Introduction to Crystal Therapy",
    descriptionFa: "آشنایی با دنیای شگفت‌انگیز کریستال‌ها و کاربرد آن‌ها در درمان. این دوره ۶ جلسه‌ای شامل شناخت ۲۰ کریستال اصلی، روش‌های پاکسازی و شارژ، ساخت شبکه‌های کریستالی و انتخاب کریستال مناسب است.",
    price: 1800000,
    instructor: "رضا کریمی",
    instructorImage: "/images/instructors/reza-karimi.jpg",
    image: "/images/courses/crystal-therapy.jpg",
    durationHours: 18,
    active: true,
    createdAt: "2024-03-10T09:00:00Z",
  },
  {
    id: "co5",
    titleFa: "شفای صدای درونی",
    titleEn: "Inner Sound Healing",
    descriptionFa: "دوره منحصر به فرد شفا با استفاده از صوت و ارتعاش. شامل آموزش کار با کاسه‌های تبتی، دیاپازون، مانترا خوانی و تکنیک‌های صوت درمانی برای پاکسازی هاله و چاکراها.",
    price: 3200000,
    instructor: "نرگس موسوی",
    instructorImage: "/images/instructors/narges-mousavi.jpg",
    image: "/images/courses/sound-healing.jpg",
    durationHours: 30,
    active: false,
    createdAt: "2024-04-01T10:00:00Z",
  },
];
