import type { Course } from "@/lib/types";

export const MOCK_COURSES: Course[] = [
  {
    id: "co1",
    titleFa: "دوره مدیتیشن مقدماتی",
    titleEn: "Beginner Meditation Course",
    descriptionFa: "یک دوره ۸ هفته‌ای کامل برای آشنایی با اصول مدیتیشن. شامل جلسات ویدیویی هفتگی، تمرین‌های عملی، فایل‌های صوتی راهنما و پشتیبانی گروهی. مناسب برای افرادی که هیچ تجربه قبلی در مدیتیشن ندارند.",
    descriptionEn: "A complete 8-week course to learn meditation principles. Includes weekly video sessions, practical exercises, audio guides, and group support.",
    price: 1500000,
    duration: "8 weeks",
    durationWeeks: 8,
    durationHours: 24,
    lessons: 12,
    level: "مقدماتی",
    language: "فارسی",
    certificate: true,
    instructor: "استاد علی محمدی",
    instructorImage: "/images/instructors/ali-mohammadi.jpg",
    image: "/images/courses/meditation-beginner.jpg",
    featured: false,
    active: true,
    createdAt: "2024-01-15T09:00:00Z",
  },
  {
    id: "co2",
    titleFa: "دوره کریستال‌درمانی",
    titleEn: "Crystal Healing Course",
    descriptionFa: "دوره جامع کریستال‌درمانی برای یادگیری کار با سنگ‌های درمانی. شامل معرفی ۲۴ سنگ، روش‌های پاکسازی، شارژ کردن و استفاده از کریستال‌ها برای بهبود سلامت.",
    descriptionEn: "Comprehensive crystal healing course to learn working with healing stones. Includes introduction to 24 crystals, cleansing methods, charging, and using crystals for health improvement.",
    price: 2100000,
    duration: "6 weeks",
    durationWeeks: 6,
    durationHours: 18,
    lessons: 8,
    level: "متوسط",
    language: "فارسی",
    certificate: true,
    instructor: "دکتر سارا احمدی",
    instructorImage: "/images/instructors/sara-ahmadi.jpg",
    image: "/images/courses/crystal-healing.jpg",
    featured: true,
    active: true,
    createdAt: "2024-02-01T10:00:00Z",
  },
  {
    id: "co3",
    titleFa: "یوگای هاتا",
    titleEn: "Hatha Yoga",
    descriptionFa: "دوره یوگای هاتا برای تقویت انعطاف‌پذیری و تعادل جسمی و ذهنی. مناسب برای همه سطوح.",
    descriptionEn: "Hatha yoga course for improving flexibility and physical and mental balance. Suitable for all levels.",
    price: 1800000,
    duration: "10 weeks",
    durationWeeks: 10,
    durationHours: 30,
    lessons: 15,
    level: "همه سطوح",
    language: "فارسی",
    certificate: true,
    instructor: "استاد رضا کریمی",
    instructorImage: "/images/instructors/reza-karimi.jpg",
    image: "/images/courses/hatha-yoga.jpg",
    featured: false,
    active: true,
    createdAt: "2024-02-15T08:00:00Z",
  },
  {
    id: "co4",
    titleFa: "مدیتیشن پیشرفته",
    titleEn: "Advanced Meditation",
    descriptionFa: "دوره مدیتیشن پیشرفته برای کسانی که تجربه قبلی دارند. شامل تکنیک‌های عمیق‌تر، مدیتیشن در حرکت و روش‌های سنتی.",
    descriptionEn: "Advanced meditation course for those with previous experience. Includes deeper techniques, moving meditation, and traditional methods.",
    price: 2500000,
    duration: "12 weeks",
    durationWeeks: 12,
    durationHours: 36,
    lessons: 18,
    level: "پیشرفته",
    language: "فارسی",
    certificate: true,
    instructor: "استاد علی محمدی",
    instructorImage: "/images/instructors/ali-mohammadi.jpg",
    image: "/images/courses/advanced-meditation.jpg",
    featured: true,
    active: true,
    createdAt: "2024-03-01T09:00:00Z",
  },
  {
    id: "co5",
    titleFa: "آرام‌سازی ذهن",
    titleEn: "Mindfulness",
    descriptionFa: "دوره ذهن‌آگاهی برای کاهش استرس و افزایش تمرکز. مناسب برای زندگی روزمره.",
    descriptionEn: "Mindfulness course for stress reduction and improved focus. Suitable for daily life.",
    price: 1200000,
    duration: "4 weeks",
    durationWeeks: 4,
    durationHours: 12,
    lessons: 6,
    level: "مقدماتی",
    language: "فارسی",
    certificate: false,
    instructor: "دکتر مریم رضوی",
    instructorImage: "/images/instructors/maryam-razavi.jpg",
    image: "/images/courses/mindfulness.jpg",
    featured: false,
    active: false,
    createdAt: "2024-03-10T11:00:00Z",
  },
];