import type { Lead } from "@/lib/types";

export const MOCK_LEADS: Lead[] = [
  { id: "l1", name: "بهاره رحیمی", email: "bahareh@example.com", phone: "09121234568", message: "سلام، من علاقه‌مند به شرکت در دوره مدیتیشن مقدماتی هستم. لطفاً اطلاعات بیشتری در مورد زمان برگزاری و هزینه‌ها ارسال کنید.", status: "new", source: "وبسایت", createdAt: "2024-05-18T09:00:00Z" },
  { id: "l2", name: "کامران صالحی", email: "kamran@example.com", phone: "09139876544", message: "آیا تورهای انرژی مناسب افراد مبتدی هم هست؟ من تجربه مدیتیشن ندارم ولی خیلی علاقه‌مندم در تور دماوند شرکت کنم.", status: "new", source: "اینستاگرام", createdAt: "2024-05-17T14:00:00Z" },
  { id: "l3", name: "پریسا ناصری", email: "parisa@example.com", phone: "09361234568", message: "سلام وقت بخیر. می‌خواستم بدونم جلسات منتورشیپ به صورت آنلاین هم برگزار میشه یا فقط حضوری هست؟", status: "contacted", source: "وبسایت", createdAt: "2024-05-16T11:30:00Z" },
  { id: "l4", name: "داوود ملکی", email: "davood@example.com", phone: "09351239877", message: "در مورد کریستال آمیتیست سوال داشتم. آیا این سنگ برای مبتدیان هم مناسبه؟ چه روشی برای پاکسازی پیشنهاد می‌کنید؟", status: "contacted", source: "تلگرام", createdAt: "2024-05-15T10:00:00Z" },
  { id: "l5", name: "آزاده فتحی", email: "azadeh@example.com", phone: "09187654322", message: "سلام، من یک مربی یوگا هستم و می‌خوام محصولات شما رو برای هنرجوهام معرفی کنم. آیا امکان همکاری یا خرید عمده وجود داره؟", status: "closed", source: "اینستاگرام", createdAt: "2024-05-14T08:30:00Z" },
  { id: "l6", name: "شهرام معدنی", email: "shahram@example.com", phone: "09221236548", message: "قیمت ست شمع چاکرا چند تومان است؟ آیا تخفیف برای خرید بیش از ۵ عدد دارید؟", status: "new", source: "وبسایت", createdAt: "2024-05-13T13:00:00Z" },
  { id: "l7", name: "گلناز پوراحمدی", email: "golnaz@example.com", phone: "09304561240", message: "سلام، پسرم ۱۲ سالشه و مشکل تمرکز داره. آیا دوره یا محصولی برای کمک به تمرکز کودکان دارید؟", status: "new", source: "وبسایت", createdAt: "2024-05-12T09:45:00Z" },
  { id: "l8", name: "مسعود کاظمی", email: "masoud@example.com", phone: "09146543219", message: "در مورد تور قشم سوال داشتم. تاریخ دقیق برگزاری تور بعدی کی هست و آیا امکان رزرو دو نفره وجود داره؟", status: "contacted", source: "تلگرام", createdAt: "2024-05-10T14:15:00Z" },
  { id: "l9", name: "رویا ابراهیمی", email: "roya@example.com", phone: "09363214587", message: "سلام من دیشب اولین مدیتیشن زندگیم رو انجام دادم و واقعاً شگفت‌زده شدم. می‌خوام محصولات بیشتری بخرم. چه پیشنهادی برای مبتدی‌ها دارید؟", status: "contacted", source: "اینستاگرام", createdAt: "2024-05-09T11:20:00Z" },
  { id: "l10", name: "فرید اسماعیلی", email: "farid@example.com", phone: "09103214568", message: "آیا بسته چوب پالو سانتو موجود دارید؟ چند روزه به دستم می‌رسه؟", status: "closed", source: "وبسایت", createdAt: "2024-05-08T08:00:00Z" },
  { id: "l11", name: "نازیلا فرهادی", email: "nazila@example.com", phone: "09331236790", message: "سلام، من در شهرستان زندگی می‌کنم. آیا ارسال به سراسر ایران دارید؟ هزینه ارسال چقدر هست؟", status: "new", source: "وبسایت", createdAt: "2024-05-07T10:30:00Z" },
  { id: "l12", name: "بیژن راد", email: "bijan@example.com", phone: "09127894562", message: "آیا دوره‌های آموزشی گواهینامه معتبر هم دارند؟ می‌خوام بعد از اتمام دوره بتونم به صورت حرفه‌ای فعالیت کنم.", status: "new", source: "اینستاگرام", createdAt: "2024-05-06T12:00:00Z" },
];
