import type { Mentor } from "@/lib/types";

export const MOCK_MENTORS: Mentor[] = [
  {
    id: "m1",
    nameFa: "استاد علی محمدی",
    nameEn: "Master Ali Mohammadi",
    bio: "بنیانگذار مرکز معنوی اورا میستیک با بیش از ۲۰ سال تجربه در زمینه مدیتیشن و انرژی درمانی. علی محمدی در هند و تبت آموزش دیده و روش‌های سنتی شرقی را با دانش مدرن ترکیب می‌کند.",
    specialization: "مدیتیشن، انرژی درمانی، چاکرا تراپی",
    pricePerSession: 850000,
    image: "/images/mentors/ali-mohammadi.jpg",
    active: true,
    rating: 4.9,
    totalSessions: 1250,
    createdAt: "2024-01-01T08:00:00Z",
  },
  {
    id: "m2",
    nameFa: "دکتر سارا احمدی",
    nameEn: "Dr. Sara Ahmadi",
    bio: "دکترای روانشناسی با گرایش درمان‌های مکمل از دانشگاه تهران. متخصص در زمینه هیپنوتراپی و تکنیک‌های تنفس عمیق. سارا رویکردی علمی به معنویت دارد.",
    specialization: "هیپنوتراپی، تنفس درمانی، روانشناسی معنوی",
    pricePerSession: 750000,
    image: "/images/mentors/sara-ahmadi.jpg",
    active: true,
    rating: 4.8,
    totalSessions: 890,
    createdAt: "2024-01-15T09:00:00Z",
  },
  {
    id: "m3",
    nameFa: "رضا کریمی",
    nameEn: "Reza Karimi",
    bio: "کریستال تراپیست حرفه‌ای با گواهینامه بین‌المللی. رضا بیش از ۱۰ سال در زمینه کار با کریستال‌ها و سنگ‌های قیمتی تجربه دارد و کارگاه‌های متعددی در سراسر ایران برگزار کرده است.",
    specialization: "کریستال تراپی، شبکه‌سازی کریستال، سنگ درمانی",
    pricePerSession: 650000,
    image: "/images/mentors/reza-karimi.jpg",
    active: true,
    rating: 4.7,
    totalSessions: 670,
    createdAt: "2024-02-01T10:00:00Z",
  },
  {
    id: "m4",
    nameFa: "نرگس موسوی",
    nameEn: "Narges Mousavi",
    bio: "متخصص صوت درمانی و موسیقی درمانی با سابقه ۱۵ سال فعالیت. نرگس در زمینه کار با کاسه‌های تبتی، گونگ و دیاپازون تخصص دارد و روش‌های درمانی سنتی ایرانی را نیز می‌شناسد.",
    specialization: "صوت درمانی، موسیقی درمانی، مانترا",
    pricePerSession: 700000,
    image: "/images/mentors/narges-mousavi.jpg",
    active: false,
    rating: 4.6,
    totalSessions: 450,
    createdAt: "2024-02-15T11:00:00Z",
  },
];
