import type { Product } from "@/lib/types";

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "p1",
    nameEn: "Amethyst Crystal",
    nameFa: "کریستال آمیتیست",
    slug: "amethyst-crystal",
    price: 280000,
    comparePrice: 350000,
    stock: 12,
    category: "stones",
    images: ["/images/products/stone-1.jpg"],
    descriptionEn: "Natural amethyst crystal for spiritual healing and meditation.",
    descriptionFa: "کریستال طبیعی آمیتیست برای درمان معنوی و مدیتیشن. این سنگ با ارتعاشات بالای خود به آرامش ذهن کمک می‌کند.",
    featured: true,
    active: true,
    createdAt: "2024-01-15T10:30:00Z",
    updatedAt: "2024-03-20T14:00:00Z",
  },
  {
    id: "p2",
    nameEn: "Rose Quartz",
    nameFa: "کوارتز صورتی",
    slug: "rose-quartz",
    price: 180000,
    stock: 25,
    category: "stones",
    images: ["/images/products/stone-2.jpg"],
    descriptionEn: "Rose quartz crystal for love and emotional healing.",
    descriptionFa: "کریستال کوارتز صورتی، سنگ عشق و محبت. مناسب برای بهبود روابط عاطفی و افزایش عشق به خود.",
    featured: true,
    active: true,
    createdAt: "2024-01-20T09:00:00Z",
    updatedAt: "2024-02-15T11:00:00Z",
  },
  {
    id: "p3",
    nameEn: "Sage Smudge Stick",
    nameFa: "دسته مریم گلی",
    slug: "sage-smudge-stick",
    price: 120000,
    stock: 40,
    category: "accessories",
    images: ["/images/products/accessory-1.jpg"],
    descriptionEn: "White sage smudge stick for energy cleansing.",
    descriptionFa: "دسته مریم گلی سفید برای پاکسازی انرژی محیط. مناسب برای شروع مدیتیشن و پاکسازی فضای شخصی.",
    featured: false,
    active: true,
    createdAt: "2024-02-01T12:00:00Z",
    updatedAt: "2024-02-01T12:00:00Z",
  },
  {
    id: "p4",
    nameEn: "Chakra Candle Set",
    nameFa: "ست شمع چاکرا",
    slug: "chakra-candle-set",
    price: 450000,
    comparePrice: 550000,
    stock: 8,
    category: "candles",
    images: ["/images/products/candle-1.jpg"],
    descriptionEn: "Set of 7 chakra candles with natural essential oils.",
    descriptionFa: "ست ۷ عددی شمع چاکرا با روغن‌های طبیعی. هر شمع مخصوص یکی از چاکراهای اصلی بدن طراحی شده است.",
    featured: true,
    active: true,
    createdAt: "2024-02-10T08:00:00Z",
    updatedAt: "2024-03-01T10:00:00Z",
  },
  {
    id: "p5",
    nameEn: "Meditation Cushion",
    nameFa: "بالش مدیتیشن",
    slug: "meditation-cushion",
    price: 650000,
    stock: 15,
    category: "accessories",
    images: ["/images/products/accessory-2.jpg"],
    descriptionEn: "Comfortable meditation cushion filled with organic buckwheat.",
    descriptionFa: "بالش مدیتیشن راحت با پرکننده گندم سیاه ارگانیک. مناسب برای نشستن‌های طولانی مدت در حین مدیتیشن.",
    featured: false,
    active: true,
    createdAt: "2024-02-15T14:00:00Z",
    updatedAt: "2024-02-15T14:00:00Z",
  },
  {
    id: "p6",
    nameEn: "Lapis Lazuli Pendant",
    nameFa: "آویز لاجورد",
    slug: "lapis-lazuli-pendant",
    price: 320000,
    stock: 18,
    category: "stones",
    images: ["/images/products/stone-3.jpg"],
    descriptionEn: "Natural lapis lazuli pendant for wisdom and truth.",
    descriptionFa: "آویز طبیعی لاجورد برای خرد و حقیقت. این سنگ قیمتی با رنگ آبی عمیق خود نمادی از دانش و آگاهی است.",
    featured: false,
    active: true,
    createdAt: "2024-02-20T11:00:00Z",
    updatedAt: "2024-03-10T09:00:00Z",
  },
  {
    id: "p7",
    nameEn: "Aura Cleansing Spray",
    nameFa: "اسپری پاکسازی هاله",
    slug: "aura-cleansing-spray",
    price: 95000,
    stock: 60,
    category: "accessories",
    images: ["/images/products/accessory-3.jpg"],
    descriptionEn: "Natural aura cleansing spray with essential oils.",
    descriptionFa: "اسپری طبیعی پاکسازی هاله با ترکیب روغن‌های ضروری. مناسب برای استفاده روزانه و پاکسازی سریع انرژی.",
    featured: false,
    active: true,
    createdAt: "2024-03-01T07:00:00Z",
    updatedAt: "2024-03-01T07:00:00Z",
  },
  {
    id: "p8",
    nameEn: "Third Eye Candle",
    nameFa: "شمع چشم سوم",
    slug: "third-eye-candle",
    price: 220000,
    stock: 20,
    category: "candles",
    images: ["/images/products/candle-2.jpg"],
    descriptionEn: "Hand-poured candle infused with amethyst and lavender.",
    descriptionFa: "شمع دست‌ساز آغشته به آمیتیست و اسطوخودوس. مناسب برای تقویت شهود و باز کردن چشم سوم.",
    featured: true,
    active: true,
    createdAt: "2024-03-05T10:00:00Z",
    updatedAt: "2024-03-15T13:00:00Z",
  },
  {
    id: "p9",
    nameEn: "Spiritual Hoodie",
    nameFa: "سوئیشرت معنوی",
    slug: "spiritual-hoodie",
    price: 780000,
    stock: 30,
    category: "clothes",
    images: ["/images/products/cloth-1.jpg"],
    descriptionEn: "Comfortable organic cotton hoodie with chakra design.",
    descriptionFa: "سوئیشرت راحت از پنبه ارگانیک با طرح چاکرا. مناسب برای استفاده روزمره و یادآوری مسیر معنوی.",
    featured: false,
    active: true,
    createdAt: "2024-03-10T09:00:00Z",
    updatedAt: "2024-03-10T09:00:00Z",
  },
  {
    id: "p10",
    nameEn: "Crystal Grid Set",
    nameFa: "ست شبکه کریستال",
    slug: "crystal-grid-set",
    price: 890000,
    comparePrice: 1100000,
    stock: 5,
    category: "stones",
    images: ["/images/products/stone-4.jpg"],
    descriptionEn: "Complete crystal grid set with 7 different crystals and sacred geometry cloth.",
    descriptionFa: "ست کامل شبکه کریستال با ۷ نوع کریستال مختلف و پارچه هندسه مقدس. مناسب برای کارهای پیشرفته انرژی.",
    featured: true,
    active: true,
    createdAt: "2024-03-15T11:00:00Z",
    updatedAt: "2024-04-01T08:00:00Z",
  },
  {
    id: "p11",
    nameEn: "Selenite Wand",
    nameFa: "عصای سلنیت",
    slug: "selenite-wand",
    price: 350000,
    stock: 0,
    category: "stones",
    images: ["/images/products/stone-5.jpg"],
    descriptionEn: "Natural selenite wand for energy clearing and charging.",
    descriptionFa: "عصای طبیعی سلنیت برای پاکسازی و شارژ انرژی. مناسب برای پاکسازی کریستال‌ها و هاله شخصی.",
    featured: false,
    active: true,
    createdAt: "2024-03-20T10:00:00Z",
    updatedAt: "2024-03-20T10:00:00Z",
  },
  {
    id: "p12",
    nameEn: "Meditation Course - Beginner",
    nameFa: "دوره مدیتیشن - مقدماتی",
    slug: "meditation-course-beginner",
    price: 1500000,
    stock: 100,
    category: "courses",
    images: ["/images/products/course-1.jpg"],
    descriptionEn: "8-week beginner meditation course with guided sessions.",
    descriptionFa: "دوره ۸ هفته‌ای مدیتیشن مقدماتی با جلسات راهنمایی شده. مناسب برای افرادی که تازه می‌خواهند مدیتیشن را شروع کنند.",
    featured: false,
    active: true,
    createdAt: "2024-04-01T08:00:00Z",
    updatedAt: "2024-04-01T08:00:00Z",
  },
  {
    id: "p13",
    nameEn: "One-on-One Mentorship",
    nameFa: "منتورشیپ خصوصی",
    slug: "one-on-one-mentorship",
    price: 2500000,
    stock: 10,
    category: "mentorship",
    images: ["/images/products/mentor-1.jpg"],
    descriptionEn: "Personalized one-on-one spiritual mentorship session.",
    descriptionFa: "جلسه منتورشیپ معنوی خصوصی و شخصی‌سازی شده. مناسب برای کسانی که به دنبال راهنمایی عمیق در مسیر معنوی خود هستند.",
    featured: true,
    active: true,
    createdAt: "2024-04-05T09:00:00Z",
    updatedAt: "2024-04-05T09:00:00Z",
  },
  {
    id: "p14",
    nameEn: "Chakra T-Shirt",
    nameFa: "تیشرت چاکرا",
    slug: "chakra-tshirt",
    price: 380000,
    stock: 45,
    category: "clothes",
    images: ["/images/products/cloth-2.jpg"],
    descriptionEn: "Soft cotton t-shirt with 7 chakra symbols print.",
    descriptionFa: "تیشرت نخی نرم با چاپ نمادهای ۷ چاکرا. مناسب برای استفاده روزمره با طراحی زیبا و معنادار.",
    featured: false,
    active: false,
    createdAt: "2024-04-10T12:00:00Z",
    updatedAt: "2024-04-10T12:00:00Z",
  },
  {
    id: "p15",
    nameEn: "Palo Santo Bundle",
    nameFa: "بسته چوب پالو سانتو",
    slug: "palo-santo-bundle",
    price: 160000,
    stock: 35,
    category: "accessories",
    images: ["/images/products/accessory-4.jpg"],
    descriptionEn: "Sustainably sourced palo santo wood bundle for smudging.",
    descriptionFa: "بسته چوب پالو سانتو با منبع پایدار برای دود دادن و پاکسازی. رایحه چوبی گرم و آرامش‌بخش.",
    featured: false,
    active: true,
    createdAt: "2024-04-15T10:00:00Z",
    updatedAt: "2024-04-15T10:00:00Z",
  },
];
