import type { Tour } from "@/lib/types";

export const MOCK_TOURS: Tour[] = [
  {
    id: "t1",
    titleFa: "تور کوهستان دماوند",
    titleEn: "Mount Damavand Tour",
    descriptionFa: "کوهنوردی به قله دماوند، بالاترین قله ایران. این تور ۵ روزه شامل راهنمای حرفه‌ای، تجهیزات کوهنوردی، اقامت در کلبه‌های کوهستان و غذاهای محلی است.",
    descriptionEn: "Mountaineering to Mount Damavand, the highest peak in Iran. This 5-day tour includes a professional guide, mountaineering equipment, mountain lodge accommodation, and local meals.",
    price: 8500000,
    destination: "دماوند، مازندران",
    dateRange: "15-20 خرداد 1403",
    startDate: "2024-06-15",
    endDate: "2024-06-20",
    durationDays: 5,
    duration: "5 days",
    location: "دماوند، مازندران",
    image: "/images/tours/damavand.jpg",
    maxCapacity: 15,
    spotsLeft: 8,
    instructor: "استاد کوهنوردی رضا کریمی",
    featured: true,
    active: true,
    createdAt: "2024-01-10T08:00:00Z",
  },
  {
    id: "t2",
    titleFa: "تور صحرای لوت",
    titleEn: "Lut Desert Tour",
    descriptionFa: "سفری به دل کویر لوت، یکی از جذاب‌ترین مکان‌های طبیعی ایران. شامل بازدید از تپه‌های ماسه‌ای، دره ستارگان، گرمابه‌های طبیعی و اقامت در کمپ لوکس.",
    descriptionEn: "A journey to the heart of Lut Desert, one of Iran's most attractive natural places. Includes visits to sand dunes, star valley, natural hot springs, and luxury camp accommodation.",
    price: 6200000,
    destination: "کرمان، لوت",
    dateRange: "1-4 تیر 1403",
    startDate: "2024-06-01",
    endDate: "2024-06-04",
    durationDays: 3,
    duration: "3 days",
    location: "کرمان، لوت",
    image: "/images/tours/lut-desert.jpg",
    maxCapacity: 20,
    spotsLeft: 12,
    instructor: "استاد طبیعت‌گردی علی محمدی",
    featured: true,
    active: true,
    createdAt: "2024-02-05T10:00:00Z",
  },
  {
    id: "t3",
    titleFa: "تور جنگل هیرکانی",
    titleEn: "Hyrcanian Forests Tour",
    descriptionFa: "گشت‌وگذار در جنگل‌های هیرکانی، میراث جهانی یونسکو. پیاده‌روی در مسیرهای طبیعی، مشاهده حیات وحش و اقامت در اقامتگاه‌های بوم‌گردی.",
    descriptionEn: "Exploring the Hyrcanian Forests, a UNESCO World Heritage site. Hiking on natural trails, wildlife watching, and staying in eco-lodges.",
    price: 4800000,
    destination: "مازندران، هیرکانی",
    dateRange: "10-12 تیر 1403",
    startDate: "2024-06-10",
    endDate: "2024-06-12",
    durationDays: 2,
    duration: "2 days",
    location: "مازندران، هیرکانی",
    image: "/images/tours/hyrcanian.jpg",
    maxCapacity: 25,
    spotsLeft: 18,
    instructor: "استاد طبیعت‌گردی سارا احمدی",
    featured: false,
    active: true,
    createdAt: "2024-02-20T09:00:00Z",
  },
  {
    id: "t4",
    titleFa: "تور کوهستان زاگرس",
    titleEn: "Zagros Mountains Tour",
    descriptionFa: "کوهنوردی در رشته‌کوه زاگرس با مناظر خیره‌کننده. این تور ۴ روزه شامل بازدید از روستاهای بومی، تجربه زندگی عشایری و غذاهای محلی است.",
    descriptionEn: "Mountaineering in the Zagros Mountains with breathtaking views. This 4-day tour includes visits to native villages, experiencing nomadic life, and local cuisine.",
    price: 5500000,
    destination: "کرمانشاه، زاگرس",
    dateRange: "20-23 تیر 1403",
    startDate: "2024-06-20",
    endDate: "2024-06-23",
    durationDays: 3,
    duration: "3 days",
    location: "کرمانشاه، زاگرس",
    image: "/images/tours/zagros.jpg",
    maxCapacity: 18,
    spotsLeft: 10,
    instructor: "استاد کوهنوردی محمد رضایی",
    featured: false,
    active: true,
    createdAt: "2024-03-01T11:00:00Z",
  },
  {
    id: "t5",
    titleFa: "تور دریاچه ارومیه",
    titleEn: "Lake Urmia Tour",
    descriptionFa: "سفری به اطراف دریاچه ارومیه، یکی از نمادهای طبیعی ایران. شامل بازدید از تپه‌های نمک، جزیره عسلیه، غروب آفتاب در دریاچه و عکاسی.",
    descriptionEn: "A journey around Lake Urmia, one of Iran's natural symbols. Includes visits to salt hills, Honey Island, sunset at the lake, and photography.",
    price: 3200000,
    destination: "ارومیه، آذربایجان غربی",
    dateRange: "5-7 مرداد 1403",
    startDate: "2024-07-05",
    endDate: "2024-07-07",
    durationDays: 2,
    duration: "2 days",
    location: "ارومیه، آذربایجان غربی",
    image: "/images/tours/urmia.jpg",
    maxCapacity: 30,
    spotsLeft: 22,
    instructor: "استاد طبیعت‌گردی مریم رضوی",
    featured: false,
    active: false,
    createdAt: "2024-03-15T08:00:00Z",
  },
];