import type { Tour } from "@/lib/types";

export const MOCK_TOURS: Tour[] = [
  {
    id: "t1",
    titleEn: "Damavand Energy Trek",
    titleFa: "تور انرژی کوه دماوند",
    descriptionFa: "یک سفر سه روزه به دامنه‌های کوه دماوند همراه با مدیتیشن‌های گروهی، یوگا در طبیعت و کارگاه‌های انرژی درمانی. این تور برای پاکسازی چاکراها و اتصال عمیق با طبیعت طراحی شده است.",
    price: 4500000,
    duration: "۳ روز",
    location: "دماوند، مازندران",
    image: "/images/tours/damavand.jpg",
    maxCapacity: 15,
    active: true,
    createdAt: "2024-02-01T10:00:00Z",
  },
  {
    id: "t2",
    titleEn: "Yazd Desert Retreat",
    titleFa: "خلوت کویر یزد",
    descriptionFa: "خلوت معنوی در قلب کویر یزد. دو شب اقامت در کمپ اکو، مدیتیشن زیر آسمان پرستاره، پیاده‌روی در تپه‌های شنی و کارگاه سکوت و خودشناسی.",
    price: 3800000,
    duration: "۲ روز",
    location: "یزد",
    image: "/images/tours/yazd.jpg",
    maxCapacity: 12,
    active: true,
    createdAt: "2024-02-15T11:00:00Z",
  },
  {
    id: "t3",
    titleEn: "Masal Forest Healing",
    titleFa: "شفای جنگل ماسال",
    descriptionFa: "سفر به جنگل‌های مه‌آلود ماسال در شمال ایران. سه شب اقامت در کلبه‌های جنگلی، مدیتیشن صبحگاهی در طبیعت، حمام جنگل و کارگاه‌های تنفس عمیق.",
    price: 5200000,
    duration: "۳ روز",
    location: "ماسال، گیلان",
    image: "/images/tours/masal.jpg",
    maxCapacity: 10,
    active: true,
    createdAt: "2024-03-01T09:00:00Z",
  },
  {
    id: "t4",
    titleEn: "Qeshm Island Spirit",
    titleFa: "روح جزیره قشم",
    descriptionFa: "کشف انرژی‌های باستانی جزیره قشم. بازدید از دره ستارگان، غارهای نمکی و جنگل‌های حرا همراه با مدیتیشن‌های هدایت شده و آیین‌های پاکسازی با آب دریا.",
    price: 6500000,
    duration: "۴ روز",
    location: "قشم، هرمزگان",
    image: "/images/tours/qeshm.jpg",
    maxCapacity: 20,
    active: true,
    createdAt: "2024-03-15T12:00:00Z",
  },
  {
    id: "t5",
    titleEn: "Alamut Castle Wisdom",
    titleFa: "حکمت قلعه الموت",
    descriptionFa: "سفر به قلعه تاریخی الموت، نماد خرد و دانش باستانی. این تور ترکیبی از تاریخ، عرفان و مدیتیشن در ارتفاعات البرز است. شامل کارگاه‌های خودشناسی و آشنایی با فلسفه شرق.",
    price: 4200000,
    duration: "۲ روز",
    location: "الموت، قزوین",
    image: "/images/tours/alamut.jpg",
    maxCapacity: 0,
    active: false,
    createdAt: "2024-04-01T08:00:00Z",
  },
];
